[package]
name = "krunner-dbus"
version = "0.1.0"
edition = "2021"
authors = ["Leah Amelia Chen <hi@pluie.me>"]
description = "Write KRunner plugins with dbus-rs."
repository = "https://github.com/pluiedev/krunner-dbus"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
dbus = "0.9.7"
dbus-crossroads = "0.5.2"
dbus-tree = "0.9.2"
